### ISSUE TITLE
Fix re-authentication triggered incorrectly, sometimes leading to leftover data in the read buffer

### ISSUE THREAD

**Issue by Jalle19** [NitorCreations/ha-extron#5]
Scenario:

1. Integration is up and running, socket is connected, all is well
2. For whatever reason, the code decides to reconnect, entering the password without the device actually having asked for the password. Depending on the password, this may lead to two lines being returned, and since we only read until the next new line, a stray line is left in the read buffer and ends up being returned in response to the next query.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/extron/media_player.py", line 98, in async_update
    volume = await self._ssp.get_volume_level()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extron/extron.py", line 137, in get_volume_level
    return int(volume)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '60-1658-01'
```

```
A1234QN <- press enter here
E13 <- triggered by A1234Q
60-1658-01 <- triggered by N
```

**Comment by Jalle19** [comment]
```
2024-11-27 12:07:37.435 WARNING (MainThread) [custom_components.extron.extron] Connection seems to be broken, will attempt to reconnect
2024-11-27 12:07:37.818 INFO (MainThread) [custom_components.extron.extron] Connected and authenticated to 10.211.0.91:23
2024-11-27 12:07:37.818 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.lounge_extron_ssp_200_media_player fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/extron/media_player.py", line 96, in async_update
    self._source = self._source_bidict.get(await self._ssp.view_input())
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extron/extron.py", line 120, in view_input
    return int(await self._device.run_command("$"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
